apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep
  labels:
    desc: deep-app-deployment
spec:
  selector:
    matchLabels:
      app: deep
  replicas: 3
  template:
    metadata:
      labels:
        app: deep
    spec:
      containers:
        - name: deep
          image: docker.io/deepmhabdi/deep-kubernetes:latest
          ports:
            - containerPort: 9000
          env: 
            - name: tree
              value: good
            - name: PORT
              value: "9000"